In [1]:
import pandas as pd
import numpy as np

In [2]:
file = pd.ExcelFile('dataPoints.xlsx')
df = file.parse('Foglio1')
df.head()

x1        x2         y
0 -1.262271  0.746859  0.461002
1 -0.804355  0.937081  0.617336
2 -1.805674  0.738389 -0.053984
3 -0.888805  0.061711  1.943678
4 -1.667562 -0.534543  2.127070

In [3]:
from sklearn.model_selection import train_test_split

# split in target and test set
def split_dataset(X, y):
    X_target, X_test, y_target, y_test = train_test_split(X, y_true.reshape(-1,1), test_size=0.15)
    X_train, X_validation, y_train, y_validation = train_test_split(X_target, y_target, test_size=0.17647)
    
    y_train = y_train.reshape(1,-1)
    y_validation = y_validation.reshape(1,-1)
    y_test = y_test.reshape(1,-1)
    
    return X_train, X_validation, X_test, y_train, y_validation, y_test

In [4]:
X = df[['x1', 'x2']].to_numpy()
y_true = df[['y']].to_numpy().reshape(1,-1)

#X_train, X_validation, X_test, y_train, y_validation, y_test = split_dataset(X, y_true)

In [5]:
def fun_RBF(X, omega):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)
    
    mat = (c-X)*(c-X)
    col = mat[:,0] + mat[:,1]
    col = np.exp(-col/(sigma**2))

    return np.dot(col, v)

In [6]:
N = 5
n = X.shape[1]
omega = np.random.randn(N + N*n)

sigma = 1
rho = 0.00001

In [7]:
#np.apply_along_axis(fun_RBF, 1, X, omega)

In [8]:
def loss(omega, X, y_true):
    y_pred = np.apply_along_axis(fun_RBF, 1, X, omega).reshape(1,-1)
    l = np.sum((y_pred - y_true)**2)/(2 * X.shape[0]) + rho * np.linalg.norm(omega)**2
    return l

In [9]:
loss(omega, X, y_true)

1.4022735109601343

In [10]:
from scipy.optimize import minimize
from time import time 

t1 = time()
res = minimize(loss, omega, args=(X, y_true))
t1 = time()-t1

In [11]:
t1

29.773724794387817

In [12]:
res

      fun: 0.13246949440292322
 hess_inv: array([[ 4.57836108e+03, -6.99822238e+02,  3.90624439e+00,
         1.95553757e+02, -4.41909701e+03, -1.70740487e+02,
        -3.57845428e+01,  5.90047460e+01,  1.36169030e+01,
        -4.08521140e-01, -6.91222375e-01, -2.18491207e+01,
         1.45018861e+00,  1.48111119e+02,  1.92973647e+01],
       [-6.99822238e+02,  9.29336400e+03,  1.05812536e+00,
        -3.78129431e+03, -4.75962964e+03, -4.94625519e+01,
        -1.03031950e+02,  1.68668908e+01, -8.75260593e+01,
         1.62765469e+01,  7.63754529e-01,  1.87764416e+02,
         7.86468061e+01, -2.40085676e+02, -1.14668702e+02],
       [ 3.90624439e+00,  1.05812536e+00,  1.56920088e+01,
        -1.07578697e-01, -3.61558372e+00,  4.20183181e-01,
        -3.02245937e-01,  2.28128831e-01, -1.72544458e-01,
        -2.26670673e+00, -2.48709967e+00,  1.40572057e-01,
        -7.54115988e-03,  3.40600207e-01, -2.04323856e-01],
       [ 1.95553757e+02, -3.78129431e+03, -1.07578697e-01,
         1.

# VECTORIZE IT

## Let's see the SIMPLE case (1 obs) and how we've done in our fun_RBF:
- 1 observation: X = [1,3]
- N = 2

In [13]:
N = 2

#X = np.array([1,3,1,3,1,3]).reshape(3,2)
X = np.array([1,5]).reshape(1,2)
omega = np.array([1, 2, 3, 2, 4, 1 ])
omega
#X = X.reshape(1,3,2)
print(X.shape)
X

(1, 2)


array([[1, 5]])

In [14]:

v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)
c

array([[3, 2],
       [4, 1]])

In [15]:
# 3-1, 2-3
# 4-1, 1-3
(c-X)

array([[ 2, -3],
       [ 3, -4]])

In [16]:
mat = (c-X)*(c-X)
mat

array([[ 4,  9],
       [ 9, 16]])

In [17]:
mat[:,0]

array([4, 9])

In [18]:
col = mat[:,0] + mat[:,1]
col

array([13, 25])

In [19]:
np.exp(-col)

array([2.26032941e-06, 1.38879439e-11])

In [20]:
col = np.exp(-col/(sigma**2))
col

array([2.26032941e-06, 1.38879439e-11])

In [21]:
np.dot(col,v)

array([2.26035718e-06])

In [22]:
fun_RBF(X, omega)

array([2.26035718e-06])

#### ok. that's the result. Let's try to vectorize it
- suppose three observations: 
X = 
    
    [[1, 2],

    [1, 4],
    
    [1, 5]]

In [23]:
N = 2

X = np.array([1,3,1,4,1,5]).reshape(3,2)
#X = np.array([1,3]).reshape(1,2)
omega = np.array([1, 2, 3, 2, 4, 1 ])
omega
#X = X.reshape(1,3,2)
print(X.shape)
X

(3, 2)


array([[1, 3],
       [1, 4],
       [1, 5]])

In [24]:
X.shape

(3, 2)

In [25]:
v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)
c

array([[3, 2],
       [4, 1]])

In [26]:
## let's concatenate all the matrices (c and x) and then "slice" them in one entire vector 

In [27]:
c_array = np.tile(c.reshape(-1),X.shape[0])
print(c_array.shape)
c_array



(12,)


array([3, 2, 4, 1, 3, 2, 4, 1, 3, 2, 4, 1])

In [28]:
np.tile(X,N)

array([[1, 3, 1, 3],
       [1, 4, 1, 4],
       [1, 5, 1, 5]])

In [29]:
X_array = np.tile(X,N).reshape(-1)
print(X_array.shape)
X_array

(12,)


array([1, 3, 1, 3, 1, 4, 1, 4, 1, 5, 1, 5])

In [30]:
# now:
# let's subtract the values of c_array and X_array
# let's obtain 1 tensor of P(=3) NX2 matrices (matrix for each observation)
# let's power the result in order compute later the norm 

In [31]:
print(c-np.array([1,3]).reshape(1,2))
print('\n')
print(c-np.array([1,4]).reshape(1,2))
print('\n')
print((c-np.array([1,5]).reshape(1,2)))

[[ 2 -1]
 [ 3 -2]]


[[ 2 -2]
 [ 3 -3]]


[[ 2 -3]
 [ 3 -4]]


In [32]:
(c_array-X_array).reshape(X.shape[0],N,2)

array([[[ 2, -1],
        [ 3, -2]],

       [[ 2, -2],
        [ 3, -3]],

       [[ 2, -3],
        [ 3, -4]]])

In [33]:
print((c-np.array([1,3]).reshape(1,2))*(c-np.array([1,3]).reshape(1,2)))
print('\n')
print((c-np.array([1,4]).reshape(1,2))*(c-np.array([1,4]).reshape(1,2)))
print('\n')
print((c-np.array([1,5]).reshape(1,2))*(c-np.array([1,5]).reshape(1,2)))

[[4 1]
 [9 4]]


[[4 4]
 [9 9]]


[[ 4  9]
 [ 9 16]]


In [34]:
mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2
mat

array([[[ 4,  1],
        [ 9,  4]],

       [[ 4,  4],
        [ 9,  9]],

       [[ 4,  9],
        [ 9, 16]]])

In [35]:
# sum the values of each matrix
col = mat[:,:,0] + mat[:,:,1]
col

array([[ 5, 13],
       [ 8, 18],
       [13, 25]])

In [36]:
col = np.exp(-col/(sigma**2))
col

array([[6.73794700e-03, 2.26032941e-06],
       [3.35462628e-04, 1.52299797e-08],
       [2.26032941e-06, 1.38879439e-11]])

In [37]:
np.dot(col, v)

array([[6.74246766e-03],
       [3.35493088e-04],
       [2.26035718e-06]])

In [38]:
# which is the right result
np.apply_along_axis(fun_RBF, 1, X, omega)

array([[6.74246766e-03],
       [3.35493088e-04],
       [2.26035718e-06]])

#### implementing now the function

In [39]:
def fun_RBF_new(X, omega):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)

    c_array = np.tile(c.reshape(-1), X.shape[0])
    X_array = np.tile(X, N).reshape(-1)

    mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2

    col = mat[:,:,0] + mat[:,:,1]
    col = np.exp(-col/(sigma**2))


    return np.dot(col,v)

In [40]:
N = 5
X = np.array([1,2,3,4,5,6]).reshape(3,2)
n = X.shape[1]
omega = np.random.randn(N + N*n)

In [41]:
np.apply_along_axis(fun_RBF, 1, X, omega)

array([[-2.00309342e-01],
       [-1.13197357e-08],
       [-7.22472931e-23]])

In [42]:
fun_RBF_new(X,omega)

array([[-2.00309342e-01],
       [-1.13197357e-08],
       [-7.22472931e-23]])

# ok, now try to minimize using the real dataset

In [222]:
X = df[['x1', 'x2']].to_numpy()
y_true = df[['y']].to_numpy().reshape(1,-1)

#X_train, X_validation, X_test, y_train, y_validation, y_test = split_dataset(X, y_true)

In [240]:
N = 20
n = X.shape[1]
omega = np.random.randn(N + N*n)

sigma = 1
rho = 0.00001

In [241]:
def loss(omega, X, y_true):
    y_pred = fun_RBF_new(X,omega).reshape(1,-1)
    l = np.sum((y_pred - y_true)**2)/(2 * X.shape[0]) + rho * np.linalg.norm(omega)**2
    return l

In [242]:
t1 = time()
res = minimize(loss, omega,jac=fun_grad_RBF, args=(X, y_true))
t1 = time()-t1
t1

1.8007078170776367

In [243]:
res

      fun: 0.01895112255653295
 hess_inv: array([[ 6.46218068e+03, -1.05025016e+03, -8.73764199e+02, ...,
         9.43528189e+00, -1.83636110e+01,  4.79563185e+01],
       [-1.05025016e+03,  8.08967689e+03,  2.65277981e+03, ...,
         6.36805254e+01,  1.34673809e+02,  9.75654468e-02],
       [-8.73764199e+02,  2.65277981e+03,  3.39349684e+03, ...,
        -6.55015797e+01,  3.65649272e+01, -3.14121142e+01],
       ...,
       [ 9.43528189e+00,  6.36805254e+01, -6.55015797e+01, ...,
         9.27894704e+01, -1.46245792e-01,  2.68491059e+00],
       [-1.83636110e+01,  1.34673809e+02,  3.65649272e+01, ...,
        -1.46245792e-01,  8.95130131e+01,  4.69244231e+01],
       [ 4.79563185e+01,  9.75654467e-02, -3.14121142e+01, ...,
         2.68491059e+00,  4.69244231e+01,  1.54367698e+02]])
      jac: array([ 1.57126952e-07, -7.48347278e-07,  1.30030240e-06,  1.00529518e-06,
       -1.97142075e-06, -6.25631717e-07, -1.29378993e-06,  1.41140412e-06,
       -1.17069204e-06, -2.86747182e-06,

## gradientone pane e vone

In [212]:
def fun_grad_RBF(omega, X, y_true):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)

    ### dE_dv
    c_array = np.tile(c.reshape(-1), X.shape[0])
    X_array = np.tile(X, N).reshape(-1)

    # ||X-c||**2 matrix 
    mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2
    col = mat[:,:,0] + mat[:,:,1]
    
    # activation function
    col = np.exp(-col/(sigma**2))

    # dE_dv
    dE_dv = np.dot((fun_RBF_new(X,omega).T - y_true), col)/X.shape[0] + 2 * rho * v.T
    dE_dv = dE_dv.reshape(-1,1)
    
    ### dE_dc
    mat1 = (-(c_array-X_array)).reshape(X.shape[0],N,2)
    mat1 = mat1[:,:,0]
    mat1 = 2 * (col*v.T*mat1) / (sigma**2)
    mat1 = np.dot((fun_RBF_new(X,omega).T - y_true), mat1)/X.shape[0]

    mat2 = (-(c_array-X_array)).reshape(X.shape[0],N,2)
    mat2 = mat2[:,:,1]
    mat2 = 2 * (col*v.T*mat2) / (sigma**2)
    mat2 = np.dot((fun_RBF_new(X,omega).T - y_true), mat2)/X.shape[0]

    fusion = np.append(mat1.T, mat2.T, axis = 1)
    
    # dE_dc
    dE_dc = fusion + 2 * rho * c
    
    return np.concatenate((dE_dv.reshape(1,-1), dE_dc.reshape(1,-1)), axis = 1).reshape(-1)

In [213]:
fun_grad_RBF(omega, X, y_true).shape

(30,)

In [221]:
t1 = time()
res = minimize(loss, omega,jac=fun_grad_RBF, args=(X, y_true))
print("Time:", time()-t1)
print("Minimized error:", res.fun)
print("Success:", res.success)

Time: 0.3963179588317871
Minimized error: 0.03965382544934101
Success: True


In [143]:
omega.shape

(30,)

In [153]:
v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)

In [154]:
### dE_dv
c_array = np.tile(c.reshape(-1), X.shape[0])
X_array = np.tile(X, N).reshape(-1)

# ||X-c||**2 matrix 
mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2
col = mat[:,:,0] + mat[:,:,1]

# activation function
col = np.exp(-col/(sigma**2))

In [157]:
col.shape

(300, 10)

In [184]:
# dE_dv
dE_dv = np.dot((fun_RBF_new(X,omega).T - y_true), col)/X.shape[0] + 2 * rho * v.T
dE_dv = dE_dv.reshape(-1,1)

In [185]:
### dE_dc
mat1 = ((c_array-X_array)).reshape(X.shape[0],N,2)
mat1 = mat1[:,:,0]
mat1 = 2 * (col*v.T*mat1) / (sigma**2)
mat1 = np.dot((fun_RBF_new(X,omega).T - y_true), mat1)/X.shape[0]

In [186]:
mat2 = ((c_array-X_array)).reshape(X.shape[0],N,2)
mat2 = mat2[:,:,1]
mat2 = 2 * (col*v.T*mat2) / (sigma**2)
mat2 = np.dot((fun_RBF_new(X,omega).T - y_true), mat2)/X.shape[0]

In [189]:
fusion = np.append(mat1.T, mat2.T, axis = 1)

# dE_dc
dE_dc = fusion + 2 * rho * c

In [191]:
c.shape

(10, 2)

In [158]:
fun_RBF_new(X,omega).T.shape

(1, 300)

In [168]:
np.array([1,1,1,1,1,2,2,2,2,2]).reshape(2,5)*np.array([1,2,3,4,5])*np.array([1,1,1,1,1,2,2,2,2,2]).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 4,  8, 12, 16, 20]])

In [164]:
mat2.shape

(1, 10)

In [166]:
np.array([1,1,1,1,1,2,2,2,2,2]).reshape(2,5)

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])