In [1]:
import pandas as pd
import numpy as np

In [844]:
file = pd.ExcelFile('dataPoints.xlsx')
df = file.parse('Foglio1')
df.head()

x1        x2         y
0 -1.262271  0.746859  0.461002
1 -0.804355  0.937081  0.617336
2 -1.805674  0.738389 -0.053984
3 -0.888805  0.061711  1.943678
4 -1.667562 -0.534543  2.127070

In [845]:
from sklearn.model_selection import train_test_split

# split in target and test set
def split_dataset(X, y):
    X_target, X_test, y_target, y_test = train_test_split(X, y_true.reshape(-1,1), test_size=0.15)
    X_train, X_validation, y_train, y_validation = train_test_split(X_target, y_target, test_size=0.17647)
    
    y_train = y_train.reshape(1,-1)
    y_validation = y_validation.reshape(1,-1)
    y_test = y_test.reshape(1,-1)
    
    return X_train, X_validation, X_test, y_train, y_validation, y_test

In [846]:
X = df[['x1', 'x2']].to_numpy()
y_true = df[['y']].to_numpy().reshape(1,-1)

#X_train, X_validation, X_test, y_train, y_validation, y_test = split_dataset(X, y_true)

In [847]:
def fun_RBF(X, omega):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)
    
    mat = (c-X)*(c-X)
    col = mat[:,0] + mat[:,1]
    col = np.exp(-col/(sigma**2))

    return np.dot(col, v)

In [848]:
N = 5
n = X.shape[1]
omega = np.random.randn(N + N*n)

sigma = 1
rho = 0.00001

In [7]:
#np.apply_along_axis(fun_RBF, 1, X, omega)

In [8]:
def loss(omega, X, y_true):
    y_pred = np.apply_along_axis(fun_RBF, 1, X, omega).reshape(1,-1)
    l = np.sum((y_pred - y_true)**2)/(2 * X.shape[0]) + rho * np.linalg.norm(omega)**2
    return l

In [9]:
loss(omega, X, y_true)

1.2406605432529185

In [10]:
from scipy.optimize import minimize
from time import time 

t1 = time()
res = minimize(loss, omega, args=(X, y_true))
t1 = time()-t1

In [11]:
t1

21.395835876464844

In [12]:
res

      fun: 0.11492077557158395
 hess_inv: array([[ 5.36618860e+03, -3.16951294e+01,  1.27470290e+01,
        -5.32237026e+03,  8.82198984e+02,  1.72177524e+02,
        -7.28343839e+01,  9.78941263e+00, -1.23041771e+01,
        -5.36404310e+00,  1.43282488e-01, -1.63682673e+02,
         4.30240903e+01, -2.39581005e+01, -2.36845959e+01],
       [-3.16951294e+01,  6.25066011e+01, -3.85678985e+01,
         3.89386283e+01,  7.24910901e+01, -2.29591609e+00,
         4.35238465e+00, -3.56893294e+01, -6.28602049e+00,
         1.20104395e+01, -5.45686612e+00,  6.86311608e-01,
         2.73195334e+00, -1.45193950e+00, -1.42546341e+00],
       [ 1.27470290e+01, -3.85678985e+01,  4.24533296e+01,
        -1.75358741e+01, -2.10944293e+01,  1.23616478e+00,
        -3.74654208e+00,  3.58176879e+01, -2.25119014e+00,
        -8.57388882e+00,  5.56646702e+00, -3.06309686e-01,
        -3.79798102e+00, -1.11992872e-01,  2.67294285e+00],
       [-5.32237026e+03,  3.89386283e+01, -1.75358741e+01,
         5.

# VECTORIZE IT

## Let's see the SIMPLE case (1 obs) and how we've done in our fun_RBF:
- 1 observation: X = [1,3]
- N = 2

In [851]:
N = 2

#X = np.array([1,3,1,3,1,3]).reshape(3,2)
X = np.array([1,5]).reshape(1,2)
omega = np.array([1, 2, 3, 2, 4, 1 ])
omega
#X = X.reshape(1,3,2)
print(X.shape)
X

(1, 2)


array([[1, 5]])

In [852]:

v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)
c

array([[3, 2],
       [4, 1]])

In [853]:
# 3-1, 2-3
# 4-1, 1-3
(c-X)

array([[ 2, -3],
       [ 3, -4]])

In [854]:
mat = (c-X)*(c-X)
mat

array([[ 4,  9],
       [ 9, 16]])

In [855]:
mat[:,0]

array([4, 9])

In [856]:
col = mat[:,0] + mat[:,1]
col

array([13, 25])

In [857]:
np.exp(-col)

array([2.26032941e-06, 1.38879439e-11])

In [858]:
col = np.exp(-col/(sigma**2))
col

array([2.26032941e-06, 1.38879439e-11])

In [859]:
np.dot(col,v)

array([2.26035718e-06])

In [860]:
fun_RBF(X, omega)

array([2.26035718e-06])

#### ok. that's the result. Let's try to vectorize it
- suppose three observations: 
X = 
    
    [[1, 2],

    [1, 4],
    
    [1, 5]]

In [861]:
N = 2

X = np.array([1,3,1,4,1,5]).reshape(3,2)
#X = np.array([1,3]).reshape(1,2)
omega = np.array([1, 2, 3, 2, 4, 1 ])
omega
#X = X.reshape(1,3,2)
print(X.shape)
X

(3, 2)


array([[1, 3],
       [1, 4],
       [1, 5]])

In [862]:
X.shape

(3, 2)

In [863]:
v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)
c

array([[3, 2],
       [4, 1]])

In [864]:
## let's concatenate all the matrices (c and x) and then "slice" them in one entire vector 

In [865]:
c_array = np.concatenate([c for _ in range(X.shape[0])]).reshape(-1)
print(c_array.shape)
c_array



(12,)


array([3, 2, 4, 1, 3, 2, 4, 1, 3, 2, 4, 1])

In [866]:
X_array = np.tile(X,N).reshape(-1)
X_array

array([1, 3, 1, 3, 1, 4, 1, 4, 1, 5, 1, 5])

In [870]:
# now:
# let's subtract the values of c_array and X_array
# let's obtain 1 tensor of P(=3) NX2 matrices (matrix for each observation)
# let's power the result in order compute later the norm 

In [871]:
print(c-np.array([1,3]).reshape(1,2))
print('\n')
print(c-np.array([1,4]).reshape(1,2))
print('\n')
print((c-np.array([1,5]).reshape(1,2)))

[[ 2 -1]
 [ 3 -2]]


[[ 2 -2]
 [ 3 -3]]


[[ 2 -3]
 [ 3 -4]]


In [872]:
(c_array-X_array).reshape(X.shape[0],N,2)

array([[[ 2, -1],
        [ 3, -2]],

       [[ 2, -2],
        [ 3, -3]],

       [[ 2, -3],
        [ 3, -4]]])

In [873]:
print((c-np.array([1,3]).reshape(1,2))*(c-np.array([1,3]).reshape(1,2)))
print('\n')
print((c-np.array([1,4]).reshape(1,2))*(c-np.array([1,4]).reshape(1,2)))
print('\n')
print((c-np.array([1,5]).reshape(1,2))*(c-np.array([1,5]).reshape(1,2)))

[[4 1]
 [9 4]]


[[4 4]
 [9 9]]


[[ 4  9]
 [ 9 16]]


In [880]:
mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2
mat

array([[[ 4,  1],
        [ 9,  4]],

       [[ 4,  4],
        [ 9,  9]],

       [[ 4,  9],
        [ 9, 16]]])

In [881]:
# sum the values of each matrix
col = mat[:,:,0] + mat[:,:,1]
col

array([[ 5, 13],
       [ 8, 18],
       [13, 25]])

In [882]:
col = np.exp(-col/(sigma**2))
col

array([[6.73794700e-03, 2.26032941e-06],
       [3.35462628e-04, 1.52299797e-08],
       [2.26032941e-06, 1.38879439e-11]])

In [883]:
np.dot(col, v)

array([[6.74246766e-03],
       [3.35493088e-04],
       [2.26035718e-06]])

In [884]:
# which is the right result
np.apply_along_axis(fun_RBF, 1, X, omega)

array([[6.74246766e-03],
       [3.35493088e-04],
       [2.26035718e-06]])

#### implementing now the function

In [885]:
def fun_RBF_new(X, omega):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)

    c_array = np.concatenate([c for _ in range(X.shape[0])]).reshape(-1)
    X_array = np.tile(X, N).reshape(-1)

    mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2

    col = mat[:,:,0] + mat[:,:,1]
    col = np.exp(-col/(sigma**2))


    return np.dot(col,v)

In [886]:
N = 5
X = np.array([1,2,3,4,5,6]).reshape(3,2)
n = X.shape[1]
omega = np.random.randn(N + N*n)

In [887]:
np.apply_along_axis(fun_RBF, 1, X, omega)

array([[-2.55452476e-01],
       [-1.99922235e-06],
       [-1.76150041e-18]])

In [888]:
fun_RBF_new(X,omega)

array([[-2.55452476e-01],
       [-1.99922235e-06],
       [-1.76150041e-18]])

# ok, now try to minimize using the real dataset

In [895]:
X = df[['x1', 'x2']].to_numpy()
y_true = df[['y']].to_numpy().reshape(1,-1)

#X_train, X_validation, X_test, y_train, y_validation, y_test = split_dataset(X, y_true)

In [903]:
N = 10
n = X.shape[1]
omega = np.random.randn(N + N*n)

sigma = 1
rho = 0.00001

In [904]:
def loss(omega, X, y_true):
    y_pred = fun_RBF_new(X,omega).reshape(1,-1)
    l = np.sum((y_pred - y_true)**2)/(2 * X.shape[0]) + rho * np.linalg.norm(omega)**2
    return l

In [905]:
t1 = time()
res = minimize(loss, omega, args=(X, y_true))
t1 = time()-t1
t1

4.746801853179932

In [906]:
res

      fun: 0.05663797072823392
 hess_inv: array([[ 3.80617553e+03, -5.45070481e+02, -5.72641172e+02,
        -1.26623361e+03, -2.37226190e+02, -1.80102721e+02,
         3.99386507e+03, -7.35532265e+02, -1.07572836e+03,
        -1.09085488e+03,  6.47681870e+01, -1.09416310e+02,
        -6.79595857e+01, -6.53598020e+01, -2.66140634e+01,
         5.45780606e+01, -8.26176518e+01,  2.97739420e+02,
         1.61287565e+02, -1.72982256e+02, -1.44830111e+01,
        -2.88268193e+01, -1.08622251e+02, -2.25484612e+01,
        -3.55123586e+01, -4.10794123e+00, -1.47827377e+02,
         2.09243901e+02,  1.99406290e+02, -9.62731086e-01],
       [-5.45070481e+02,  4.84262448e+03,  1.60586844e+03,
        -3.75050608e+02, -2.31504613e+03, -3.38039028e+03,
        -6.05519273e+02,  1.03165069e+03, -2.50015586e+01,
         1.49515417e+03, -1.30469818e+02, -1.17791598e+02,
        -4.25337870e+01,  1.14590374e+02,  7.00631919e+01,
         5.44047804e+00, -1.38118084e+02,  6.58148291e+01,
         4.44