In [1]:
import pandas as pd
import numpy as np

In [844]:
file = pd.ExcelFile('dataPoints.xlsx')
df = file.parse('Foglio1')
df.head()

x1        x2         y
0 -1.262271  0.746859  0.461002
1 -0.804355  0.937081  0.617336
2 -1.805674  0.738389 -0.053984
3 -0.888805  0.061711  1.943678
4 -1.667562 -0.534543  2.127070

In [845]:
from sklearn.model_selection import train_test_split

# split in target and test set
def split_dataset(X, y):
    X_target, X_test, y_target, y_test = train_test_split(X, y_true.reshape(-1,1), test_size=0.15)
    X_train, X_validation, y_train, y_validation = train_test_split(X_target, y_target, test_size=0.17647)
    
    y_train = y_train.reshape(1,-1)
    y_validation = y_validation.reshape(1,-1)
    y_test = y_test.reshape(1,-1)
    
    return X_train, X_validation, X_test, y_train, y_validation, y_test

In [846]:
X = df[['x1', 'x2']].to_numpy()
y_true = df[['y']].to_numpy().reshape(1,-1)

#X_train, X_validation, X_test, y_train, y_validation, y_test = split_dataset(X, y_true)

In [847]:
def fun_RBF(X, omega):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)
    
    mat = (c-X)*(c-X)
    col = mat[:,0] + mat[:,1]
    col = np.exp(-col/(sigma**2))

    return np.dot(col, v)

In [848]:
N = 5
n = X.shape[1]
omega = np.random.randn(N + N*n)

sigma = 1
rho = 0.00001

In [7]:
#np.apply_along_axis(fun_RBF, 1, X, omega)

In [8]:
def loss(omega, X, y_true):
    y_pred = np.apply_along_axis(fun_RBF, 1, X, omega).reshape(1,-1)
    l = np.sum((y_pred - y_true)**2)/(2 * X.shape[0]) + rho * np.linalg.norm(omega)**2
    return l

In [9]:
loss(omega, X, y_true)

1.2406605432529185

In [10]:
from scipy.optimize import minimize
from time import time 

t1 = time()
res = minimize(loss, omega, args=(X, y_true))
t1 = time()-t1

In [11]:
t1

21.395835876464844

In [12]:
res

      fun: 0.11492077557158395
 hess_inv: array([[ 5.36618860e+03, -3.16951294e+01,  1.27470290e+01,
        -5.32237026e+03,  8.82198984e+02,  1.72177524e+02,
        -7.28343839e+01,  9.78941263e+00, -1.23041771e+01,
        -5.36404310e+00,  1.43282488e-01, -1.63682673e+02,
         4.30240903e+01, -2.39581005e+01, -2.36845959e+01],
       [-3.16951294e+01,  6.25066011e+01, -3.85678985e+01,
         3.89386283e+01,  7.24910901e+01, -2.29591609e+00,
         4.35238465e+00, -3.56893294e+01, -6.28602049e+00,
         1.20104395e+01, -5.45686612e+00,  6.86311608e-01,
         2.73195334e+00, -1.45193950e+00, -1.42546341e+00],
       [ 1.27470290e+01, -3.85678985e+01,  4.24533296e+01,
        -1.75358741e+01, -2.10944293e+01,  1.23616478e+00,
        -3.74654208e+00,  3.58176879e+01, -2.25119014e+00,
        -8.57388882e+00,  5.56646702e+00, -3.06309686e-01,
        -3.79798102e+00, -1.11992872e-01,  2.67294285e+00],
       [-5.32237026e+03,  3.89386283e+01, -1.75358741e+01,
         5.

# VECTORIZE IT

## Let's see the SIMPLE case (1 obs) and how we've done in our fun_RBF:
- 1 observation: X = [1,3]
- N = 2

In [851]:
N = 2

#X = np.array([1,3,1,3,1,3]).reshape(3,2)
X = np.array([1,5]).reshape(1,2)
omega = np.array([1, 2, 3, 2, 4, 1 ])
omega
#X = X.reshape(1,3,2)
print(X.shape)
X

(1, 2)


array([[1, 5]])

In [852]:

v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)
c

array([[3, 2],
       [4, 1]])

In [853]:
# 3-1, 2-3
# 4-1, 1-3
(c-X)

array([[ 2, -3],
       [ 3, -4]])

In [854]:
mat = (c-X)*(c-X)
mat

array([[ 4,  9],
       [ 9, 16]])

In [855]:
mat[:,0]

array([4, 9])

In [856]:
col = mat[:,0] + mat[:,1]
col

array([13, 25])

In [857]:
np.exp(-col)

array([2.26032941e-06, 1.38879439e-11])

In [858]:
col = np.exp(-col/(sigma**2))
col

array([2.26032941e-06, 1.38879439e-11])

In [859]:
np.dot(col,v)

array([2.26035718e-06])

In [860]:
fun_RBF(X, omega)

array([2.26035718e-06])

#### ok. that's the result. Let's try to vectorize it
- suppose three observations: 
X = 
    
    [[1, 2],

    [1, 4],
    
    [1, 5]]

In [924]:
N = 2

X = np.array([1,3,1,4,1,5]).reshape(3,2)
#X = np.array([1,3]).reshape(1,2)
omega = np.array([1, 2, 3, 2, 4, 1 ])
omega
#X = X.reshape(1,3,2)
print(X.shape)
X

(3, 2)


array([[1, 3],
       [1, 4],
       [1, 5]])

In [925]:
X.shape

(3, 2)

In [926]:
v = omega[0:N].reshape(N, 1)
c = omega[N: ].reshape(N, n)
c

array([[3, 2],
       [4, 1]])

In [927]:
## let's concatenate all the matrices (c and x) and then "slice" them in one entire vector 

In [933]:
c_array = np.tile(c.reshape(-1),X.shape[0])
print(c_array.shape)
c_array



(12,)


array([3, 2, 4, 1, 3, 2, 4, 1, 3, 2, 4, 1])

In [934]:
X_array = np.tile(X,N).reshape(-1)
print(X_array.shape)
X_array

(12,)


array([1, 3, 1, 3, 1, 4, 1, 4, 1, 5, 1, 5])

In [935]:
# now:
# let's subtract the values of c_array and X_array
# let's obtain 1 tensor of P(=3) NX2 matrices (matrix for each observation)
# let's power the result in order compute later the norm 

In [936]:
print(c-np.array([1,3]).reshape(1,2))
print('\n')
print(c-np.array([1,4]).reshape(1,2))
print('\n')
print((c-np.array([1,5]).reshape(1,2)))

[[ 2 -1]
 [ 3 -2]]


[[ 2 -2]
 [ 3 -3]]


[[ 2 -3]
 [ 3 -4]]


In [937]:
(c_array-X_array).reshape(X.shape[0],N,2)

array([[[ 2, -1],
        [ 3, -2]],

       [[ 2, -2],
        [ 3, -3]],

       [[ 2, -3],
        [ 3, -4]]])

In [938]:
print((c-np.array([1,3]).reshape(1,2))*(c-np.array([1,3]).reshape(1,2)))
print('\n')
print((c-np.array([1,4]).reshape(1,2))*(c-np.array([1,4]).reshape(1,2)))
print('\n')
print((c-np.array([1,5]).reshape(1,2))*(c-np.array([1,5]).reshape(1,2)))

[[4 1]
 [9 4]]


[[4 4]
 [9 9]]


[[ 4  9]
 [ 9 16]]


In [939]:
mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2
mat

array([[[ 4,  1],
        [ 9,  4]],

       [[ 4,  4],
        [ 9,  9]],

       [[ 4,  9],
        [ 9, 16]]])

In [940]:
# sum the values of each matrix
col = mat[:,:,0] + mat[:,:,1]
col

array([[ 5, 13],
       [ 8, 18],
       [13, 25]])

In [941]:
col = np.exp(-col/(sigma**2))
col

array([[6.73794700e-03, 2.26032941e-06],
       [3.35462628e-04, 1.52299797e-08],
       [2.26032941e-06, 1.38879439e-11]])

In [942]:
np.dot(col, v)

array([[6.74246766e-03],
       [3.35493088e-04],
       [2.26035718e-06]])

In [943]:
# which is the right result
np.apply_along_axis(fun_RBF, 1, X, omega)

array([[6.74246766e-03],
       [3.35493088e-04],
       [2.26035718e-06]])

#### implementing now the function

In [948]:
def fun_RBF_new(X, omega):
    
    v = omega[0:N].reshape(N, 1)
    c = omega[N: ].reshape(N, n)

    c_array = np.tile(c.reshape(-1), X.shape[0])
    X_array = np.tile(X, N).reshape(-1)

    mat = ((c_array-X_array).reshape(X.shape[0],N,2))**2

    col = mat[:,:,0] + mat[:,:,1]
    col = np.exp(-col/(sigma**2))


    return np.dot(col,v)

In [949]:
N = 5
X = np.array([1,2,3,4,5,6]).reshape(3,2)
n = X.shape[1]
omega = np.random.randn(N + N*n)

In [950]:
np.apply_along_axis(fun_RBF, 1, X, omega)

array([[-4.25492949e-01],
       [-5.92901153e-04],
       [-1.76185177e-13]])

In [951]:
fun_RBF_new(X,omega)

array([[-4.25492949e-01],
       [-5.92901153e-04],
       [-1.76185177e-13]])

# ok, now try to minimize using the real dataset

In [952]:
X = df[['x1', 'x2']].to_numpy()
y_true = df[['y']].to_numpy().reshape(1,-1)

#X_train, X_validation, X_test, y_train, y_validation, y_test = split_dataset(X, y_true)

In [953]:
N = 10
n = X.shape[1]
omega = np.random.randn(N + N*n)

sigma = 1
rho = 0.00001

In [954]:
def loss(omega, X, y_true):
    y_pred = fun_RBF_new(X,omega).reshape(1,-1)
    l = np.sum((y_pred - y_true)**2)/(2 * X.shape[0]) + rho * np.linalg.norm(omega)**2
    return l

In [955]:
t1 = time()
res = minimize(loss, omega, args=(X, y_true))
t1 = time()-t1
t1

3.541853904724121

In [956]:
res

      fun: 0.03618465925406189
 hess_inv: array([[ 9.86135911e+03, -1.86421605e+03,  4.67627887e+03,
         5.02335600e+02,  4.08317331e+01,  1.79287617e+03,
         2.27364990e+03, -2.85825880e+03,  3.08494692e+03,
        -2.31612053e+03, -1.78878991e+02,  3.76045925e+01,
         2.48915416e+02,  5.38320130e+01, -7.52854249e+01,
        -2.06273764e+02,  2.10475658e+01, -2.13421689e+02,
        -1.73359580e+02, -8.67917529e+01,  9.13117406e+01,
        -5.33414854e+01,  7.08433268e+00, -1.72413952e+02,
         1.01440387e+02, -9.75405538e+01,  4.32826122e+01,
         4.66715459e+01, -2.91752145e+02, -9.33339112e+01],
       [-1.86421605e+03,  1.07949093e+04,  1.40456948e+03,
        -9.87994552e+02,  6.85861622e+02,  2.58241634e+02,
        -1.39097366e+02,  1.39228431e+03, -2.50886108e+03,
        -8.20249722e+02,  7.90597241e+01, -1.60472893e+01,
        -9.18311101e+01,  4.83076907e+02,  1.33566182e+01,
        -7.01893049e+01,  4.11276122e+01,  1.44339884e+02,
        -8.28